<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SurLenovo" failures="2" tests="12" name="ds.algo.testcases.TestQueue" time="61.234" errors="0" timestamp="2022-09-15T12:26:23 PDT" skipped="0">
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationusingcollectionsdeque" time="4.465"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestQueueOperations" time="4.605"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationusingarrayTryHere" time="4.855"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestQueueOperationsTryHere" time="5.440"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestStarted" time="4.515"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationusingarray" time="4.615"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationusingcollectionsdequeFailed" time="4.513">
    <failure message="expected [Implementation using collections.deque  Art] but found [Implementation using collections.deque]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Implementation using collections.deque  Art] but found [Implementation using collections.deque]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ds.algo.testcases.TestQueue.TestImplementationusingcollectionsdequeFailed(TestQueue.java:119)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestImplementationusingcollectionsdequeFailed -->
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestPracticeQuestions" time="5.152"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationofQueueinPython" time="5.820"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestQueueOperationsFailed" time="4.414">
    <failure message="expected [Queue Operations sucess] but found [Queue Operations]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Queue Operations sucess] but found [Queue Operations]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ds.algo.testcases.TestQueue.TestQueueOperationsFailed(TestQueue.java:162)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestQueueOperationsFailed -->
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationofQueueinPythonTryHere" time="7.114"/>
  <system-out/>
  <testcase classname="ds.algo.testcases.TestQueue" name="TestImplementationusingcollectionsdequeTryHere" time="5.726"/>
  <system-out/>
</testsuite> <!-- ds.algo.testcases.TestQueue -->
